/* =========================================================================
   Exchange Online Mailbox Analytics Dashboard
   01_schema_and_load_ORACLE.sql
   Oracle SQL version (tested against Oracle 12c+/19c/21c syntax)
   ========================================================================= */

-- Oracle doesn't use "CREATE DATABASE" the way SQL Server does.
-- Run this as a user/schema that already exists (e.g. your own schema in
-- Oracle Live SQL, or a schema your DBA created for you), OR create a new
-- schema/user first:
--   CREATE USER exo_analytics IDENTIFIED BY YourPassword123;
--   GRANT CONNECT, RESOURCE, CREATE VIEW TO exo_analytics;
--   ALTER USER exo_analytics QUOTA UNLIMITED ON USERS;
-- Then connect AS that user before running the rest of this script.

-- -------------------------------------------------------------------------
-- Dimension: Departments
-- -------------------------------------------------------------------------
DROP TABLE Departments CASCADE CONSTRAINTS PURGE;
CREATE TABLE Departments (
    DepartmentID    NUMBER PRIMARY KEY,
    Department      VARCHAR2(100) NOT NULL
);

-- -------------------------------------------------------------------------
-- Dimension: Licenses
-- -------------------------------------------------------------------------
DROP TABLE Licenses CASCADE CONSTRAINTS PURGE;
CREATE TABLE Licenses (
    LicenseSKU       VARCHAR2(50) PRIMARY KEY,
    LicenseName      VARCHAR2(100) NOT NULL,
    MonthlyCostUSD   NUMBER(10,2) NOT NULL,
    MailboxQuotaGB   NUMBER NOT NULL
);

-- -------------------------------------------------------------------------
-- Fact/Dimension: Mailboxes (one row per mailbox - current-state snapshot)
-- -------------------------------------------------------------------------
DROP TABLE Mailboxes CASCADE CONSTRAINTS PURGE;
CREATE TABLE Mailboxes (
    MailboxID              VARCHAR2(20) PRIMARY KEY,
    DisplayName             VARCHAR2(200) NOT NULL,
    EmailAddress            VARCHAR2(200) NOT NULL,
    DepartmentID            NUMBER NOT NULL REFERENCES Departments(DepartmentID),
    Country                 VARCHAR2(100) NOT NULL,
    LicenseSKU              VARCHAR2(50) NOT NULL REFERENCES Licenses(LicenseSKU),
    MailboxType             VARCHAR2(20) NOT NULL,   -- User, Shared, Room, Equipment
    MailboxSizeGB           NUMBER(10,2) NOT NULL,
    QuotaGB                 NUMBER NOT NULL,
    ItemCount                NUMBER NOT NULL,
    CreatedDate             DATE NOT NULL,
    LastLogonDate           DATE NOT NULL,
    DaysSinceLastLogon      NUMBER NOT NULL,
    IsActive                NUMBER(1) NOT NULL CHECK (IsActive IN (0,1)),          -- Oracle has no native BIT/BOOLEAN column type pre-23c
    LitigationHoldEnabled   NUMBER(1) NOT NULL CHECK (LitigationHoldEnabled IN (0,1)),
    ArchiveEnabled          NUMBER(1) NOT NULL CHECK (ArchiveEnabled IN (0,1)),
    PercentQuotaUsed        NUMBER(5,1) NOT NULL
);

-- -------------------------------------------------------------------------
-- Fact: Mail Flow (daily grain per mailbox)
-- -------------------------------------------------------------------------
DROP TABLE MailFlow CASCADE CONSTRAINTS PURGE;
CREATE TABLE MailFlow (
    MailFlowID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Oracle 12c+ identity column (replaces SQL Server IDENTITY(1,1))
    MailboxID        VARCHAR2(20) NOT NULL REFERENCES Mailboxes(MailboxID),
    FlowDate         DATE NOT NULL,
    EmailsSent       NUMBER NOT NULL,
    EmailsReceived   NUMBER NOT NULL,
    SpamDetected     NUMBER NOT NULL,
    FailedEmails     NUMBER NOT NULL,
    SpamRatePct      NUMBER(5,2)                                         -- pre-computed, see project notes
);
CREATE INDEX IX_MailFlow_Date ON MailFlow(FlowDate);
CREATE INDEX IX_MailFlow_Mailbox ON MailFlow(MailboxID);

/* -------------------------------------------------------------------------
   Loading data from CSV in Oracle: there is no BULK INSERT statement.
   Two common options:

   OPTION A - SQL*Loader (classic, works everywhere, run from command line):
   Create a control file departments.ctl:

       LOAD DATA
       INFILE 'departments.csv'
       INTO TABLE Departments
       FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
       TRAILING NULLCOLS
       ( DepartmentID, Department )

   Then from a terminal (not inside SQL*Plus):
       sqlldr userid=exo_analytics/YourPassword123 control=departments.ctl

   Repeat with matching .ctl files for licenses.csv, mailboxes.csv, mail_flow.csv
   (skip the header row with SKIP=1 in the sqlldr call, or add it to the .ctl file).

   OPTION B - External Table (lets Oracle query the CSV directly, no load step):

   CREATE TABLE Departments_ext (
       DepartmentID NUMBER,
       Department   VARCHAR2(100)
   )
   ORGANIZATION EXTERNAL (
       TYPE ORACLE_LOADER
       DEFAULT DIRECTORY data_dir          -- a DIRECTORY object pointing at your CSV folder
       ACCESS PARAMETERS (
           RECORDS DELIMITED BY NEWLINE
           SKIP 1
           FIELDS TERMINATED BY ','
           OPTIONALLY ENCLOSED BY '"'
       )
       LOCATION ('departments.csv')
   )
   REJECT LIMIT UNLIMITED;

   -- Then simply:
   INSERT INTO Departments SELECT * FROM Departments_ext;

   Option B is usually easier if you're working in something like Oracle Live SQL
   or a cloud Autonomous Database, since you skip the command-line SQL*Loader step.
   ------------------------------------------------------------------------- */
